version: "3"
services:
  builder:
      image: aufait-builder:latest
      depends_on:
        - db
      links:
        - db
      build:
        context: ./builder
        dockerfile: Dockerfile
  listener:
      depends_on:
        - db
      links:
        - db
      image: aufait-listener:latest
      ports:
        - "8080:8080"
      build:
        context: ./listener
        dockerfile: Dockerfile
  db:
      image: mongo
      ports:
        - "27017:27017"
      command: mongod --smallfiles
